# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-03 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20170202_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlink',
            name='link_type',
            field=models.CharField(blank=True, choices=[(('likes',), 'Likes'), ('saved', 'Bookmarked'), ('been_to', 'Been-to')], max_length=32, null=True),
        ),
    ]
