# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-08 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlinks', '0003_auto_20170203_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlink',
            name='link_type',
            field=models.CharField(blank=True, choices=[(('likes',), 'Likes'), ('saved', 'Bookmarked'), ('been_to', 'Visited')], max_length=32, null=True),
        ),
    ]
